services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${PG_USR:-postgres}
      POSTGRES_PASSWORD: ${PG_PW:-1234}
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.hostname==pi-data
  backend:
    image: pi-head.local:5000/james_backend:latest
    build: ./backend
    environment:
      DATABASE_URL: postgres://${PG_USR:-postgres}:${PG_PW:-1234}@db/database
    ports:
      - "42069:42069"
    depends_on:
      - db
  frontend:
    image: pi-head.local:5000/james_frontend:latest
    build: ./frontend
    ports:
      - "80:80"
volumes:
  db_data:
