services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:1234@db/database
    ports:
      - "42069:42069"
    depends_on:
      - db
  build_frontend:
    build: ./frontend
    ports:
      - "80:80"
volumes:
  db_data:
