name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: sudo docker compose build
    - name: Push Docker image
      run: sudo docker compose push
    - name: Deploy
      run: PG_USR=${{secrets.POSTGRES_USER}} PG_PW=${{secrets.POSTGRES_PASSWORD}} sudo docker stack deploy --compose-file compose.yml james_tools
    
      
