name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build frontend Docker image
      run: sudo docker build ./frontend -t localhost:5000/james-tools-frontend
    - name: Push frontend Docker image
      run: sudo docker push localhost:5000/james-tools-frontend
    - name: Build backend Docker image
      run: sudo docker build ./backend -t localhost:5000/james-tools-backend
    - name: Push backend Docker image
      run: sudo docker push localhost:5000/james-tools-backend
    
      
