name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: sudo docker build ./frontend -t localhost:5000/james-tools-frontend
    - name: Push the Docker image
      run: sudo docker push localhost:5000/james-tools-frontend
      
